# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f996126c0deea960ce66ea34f8e1e1a89e87f7a4ddef97b2a74ef76e0c482a65f1a1e37d3b20157915aaab2421a73ffad240ab169a4f5eb639f9be4b5453100

test:
  secret_key_base: 453867403ec6c87f576cd5014f0484f0df7210821eb5e151e21378dfa4b56f203da35d4c9ff6201a509cad3bb8477e0371bda1b34f1086570f47a8846ed51c42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
